name: Pure Windows Build
on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch: # 允许你在 Actions 页面手动点击按钮触发

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: install dependencies
        run: |
          npm install -g yarn
          yarn install

      - name: build tauri app
        run: yarn tauri build --bundles none

      - name: Upload Windows EXE
        uses: actions/upload-artifact@v4
        with:
          name: my-private-neuz
          path: src-tauri/target/release/
